### ISSUE TITLE
Add functionality to add images of food.

### ISSUE THREAD

**Issue by rahgurung** [gurungrahul2/FoodShala#5]
This is related to #4

**Comment by rahgurung** [comment]
simply use a folder to save image maybe `assets/img` or something like that and save the name of the image in DB, make sure each image has a unique name, best would be a combination of timestamp and name of the user or find a better alternative.

**Comment by tadeubdev** [comment]
I will try to do it after.

**Comment by rahgurung** [comment]
@tadeubarbosa go ahead :)
