### ISSUE TITLE
Add editorconfig at this project

### ISSUE THREAD

**Issue by tadeubdev** [gurungrahul2/FoodShala#9]
Adding [editorconfig](https://editorconfig.org/) at this project some rules will be preserved.

Maybe will can be create like this:

````editorconfig
root = true

[*]
indent_style = space
indent_size = 2
end_of_line = crlf
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = true
````

The `editorconfig` have compatibility with various editors/IDEs and similars. This can be see [here](https://editorconfig.org/).

**Comment by rahgurung** [comment]
@tadeubarbosa  looks like a nice idea, thanks.

**Comment by rahgurung** [comment]
Can you give a PR ? @tadeubarbosa

**Comment by tadeubdev** [comment]
Yes! I will work in that!

**Comment by rahgurung** [comment]
Thanks

**Comment by tadeubdev** [comment]
You're welcome!
I'm correcting the indentation in some files and will send it...

**Comment by rahgurung** [comment]
Since StyleCI is integrated, we don't really use this for now.
